AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '*.gemspec'

Bundler/GemFilename:
  EnforcedStyle: gems.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'
    - 'spec/shared_examples/**/*.rb'

Layout/LineLength:
  Max: 80

Lint/EmptyBlock:
  Exclude:
    - spec/rack_on_lambda/adapters/responses/rest_api_response.rb
    - spec/rack_on_lambda/adapters/rest_api_spec.rb

Naming/FileName:
  Exclude:
    - lib/rack-on-lambda.rb
    - spec/rack-on-lambda_spec.rb

Style/Documentation:
  Enabled: false
